# Generated by Django 5.2.7 on 2025-10-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'db_table': 'cancha',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id_equipamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'db_table': 'equipamiento',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('valor', models.BigIntegerField(blank=True, null=True)),
                ('porcentaje', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promocion',
            },
        ),
        migrations.CreateModel(
            name='TipoCancha',
            fields=[
                ('id_tipo_cancha', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipo de Cancha',
                'verbose_name_plural': 'Tipos de Cancha',
                'db_table': 'tipo_cancha',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='pass', max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('subtotal', models.BigIntegerField()),
                ('descuento', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('C', 'Cancelada')], max_length=1)),
                ('cancha', models.ForeignKey(db_column='cancha_id_cancha', on_delete=django.db.models.deletion.CASCADE, to='core.cancha')),
                ('horario', models.ForeignKey(db_column='horario_id_horario', on_delete=django.db.models.deletion.CASCADE, to='core.horario')),
                ('promocion', models.ForeignKey(blank=True, db_column='promocion_id_promocion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocion')),
                ('usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_cancha',
            field=models.ForeignKey(db_column='tipo_cancha_id_tipo_cancha', on_delete=django.db.models.deletion.CASCADE, to='core.tipocancha'),
        ),
        migrations.CreateModel(
            name='ReservaEquipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('equipamiento', models.ForeignKey(db_column='equipamiento_id_equipamiento', on_delete=django.db.models.deletion.CASCADE, to='core.equipamiento')),
                ('reserva', models.ForeignKey(db_column='reserva_id_reserva', on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
            options={
                'verbose_name': 'Reserva de Equipamiento',
                'verbose_name_plural': 'Reservas de Equipamiento',
                'db_table': 'reserva_equipamiento',
                'unique_together': {('equipamiento', 'reserva')},
            },
        ),
    ]
