# Generated by Django 3.1.2 on 2025-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
