# Generated by Django 3.1.2 on 2025-11-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251101_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='tipos_cancha',
            field=models.ManyToManyField(blank=True, db_table='equipamiento_tipo_cancha', related_name='equipamientos', to='core.TipoCancha'),
        ),
    ]
