# Generated by Django 3.1.2 on 2025-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipamiento_tipos_cancha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='valor',
        ),
        migrations.AddField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='descuento_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
