# Generated by Django 3.1.2 on 2025-11-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251102_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField()),
                ('cancha', models.ForeignKey(db_column='cancha_id_cancha', on_delete=django.db.models.deletion.CASCADE, to='core.cancha')),
                ('horario', models.ForeignKey(db_column='horario_id_horario', on_delete=django.db.models.deletion.CASCADE, to='core.horario')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifa',
                'unique_together': {('cancha', 'horario')},
            },
        ),
    ]
