# Generated by Django 3.1.2 on 2025-11-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
