# Generated by Django 3.1.2 on 2025-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cancha_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
