from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('promociones/', views.promociones, name='promociones'),
    path('registro/', views.registro, name='registro'),
    path('olvide_contrasena/', views.olvide_contrasena, name='olvide_contrasena'),
    path('restablecer/<uidb64>/<token>/', views.restablecer_contrasena, name='restablecer_contrasena'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('canchas/', views.canchas, name='canchas'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('reserva/<int:id_cancha>/', views.reserva, name='reserva'),
    path('comprobante/', views.comprobante, name='comprobante'),
    path('cuenta/', views.cuenta, name='cuenta'),
    path('modificarCuenta/', views.modificarCuenta, name='modificarCuenta'),
    path('historialReserva/', views.historialReserva, name='historialReserva'),
    path('detalleReserva/<int:id_reserva>/', views.detalleReserva, name='detalleReserva'),
    path('confirmar_reserva/', views.confirmar_reserva, name='confirmar_reserva'),
    path('api/promocion/<str:codigo>/', views.validar_promocion, name='validar_promocion'),
    path('api/horarios_ocupados/', views.api_horarios_ocupados, name='api_horarios_ocupados'),
    path('crear_checkout/', views.crear_checkout, name='crear_checkout'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('pago_fallido/', views.pago_fallido, name='pago_fallido'),
    path('api/clima/', views.obtener_clima, name='obtener_clima'),
    path('centroGestion/', views.centroGestion, name='centroGestion'),
    path('gestionComercial/', views.gestionComercial, name='gestionComercial'),
    path('gestionCuentas/', views.gestionCuentas, name='gestionCuentas'),
    path('crudOperadores/', views.crudOperadores, name='crudOperadores'),
    path('crudAdministradores/', views.crudAdministradores, name='crudAdministradores'),
    path('crudUsuarios/', views.crudUsuarios, name='crudUsuarios'),
    path('crudCanchas/', views.crudCanchas, name='crudCanchas'),
    path('canchas/agregar/', views.cancha_create, name='cancha_add'),
    path('canchas/<int:pk>/editar/', views.cancha_edit, name='cancha_edit'),
    path('canchas/<int:pk>/eliminar/', views.cancha_delete, name='cancha_delete'),
    path('crudReservas/', views.crudReservas, name='crudReservas'),
    path('crudEquipamientos/', views.crudEquipamientos, name='crudEquipamientos'),
    path('crudTarifas/', views.crudTarifas, name='crudTarifas'),
    path('crudPromociones/', views.crudPromociones, name='crudPromociones'),
    path('crudHorarios/', views.crudHorarios, name='crudHorarios'),
]
